// <auto-generated />
namespace Movie_Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateModelsasadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateModelsasadas));
        
        string IMigrationMetadata.Id
        {
            get { return "201812171026341_updateModelsasadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
